#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

pip install --upgrade pip
python3 -m pip install --requirement requirements.txt

#if [ ! -f ./local.env ]; then
#  cp ./.devcontainer/configuration-template.yaml ./.devcontainer/configuration.yaml
#fi

#container install

#if [ ! ${REQUIREMENTS_TXT} == "none" ]; then
#    pip3 install --user -r requirements_${REQUIREMENTS_TXT}.txt
#fi
