name: Pull Request Flow
on: pull_request

concurrency: mastertherm
permissions:
  contents: write
  pull-requests: write

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  validate:
    name: Validate
    uses: ./.github/workflows/validate.yml

  merge:
    name: Merge Debendabot Request
    needs: [lint, validate]
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve a PR
        # run: gh pr review --approve "$PR_URL"
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}